SELECT*FROM Movies
SELECT*FROM Actors
SELECT*FROM Directors
SELECT*FROM Genres
SELECT*FROM MovieGenres
SELECT*FROM MovieActors
SELECT*FROM Rooms
SELECT*FROM Seats
SELECT*FROM SeatTypes
SELECT*FROM showtimes
SELECT*FROM Users

SELECT*FROM Orders
SELECT*FROM OrderServices
SELECT*FROM OrderTickets




  
